### PR TITLE
Optimizations

### PR DESCRIPTION
**Pull request by asterite**
@costajob Hi!

I saw your tweet (can't find it now) saying that the Crystal version was twice as fast, but you wondered why it wasn't faster. I profiled your app and found some bottlenecks, then I improved them :-)

In summary, the changes are:

1. Calling `@catalog.keys` on every request is slow, as this builds a huge array for the keys. This is not really needed, as the keys are already in `@catalog` and can be traversed with `each`, `reduce` and `find` without allocating extra memory.
2. Use `to_json(io)` to directly write the JSON output to the response. This is the approach the whole standard library takes: `to_s`, `to_json` and `to_yaml` all have an overload that writes directly to an IO. This avoids extra memory allocations (it avoids creating an intermediate string only to dump it to the response and then wait for the GC to collect it)
3. Change some types to structs instead of classes. The many Rules types only define behaviour, no real data, and they are immutable, so it's best to define them as struct. These then will be allocated on the stack, not on the heap, and avoid extra memory allocations.

As you can see, the most important point is to avoid extra memory allocations: these are slow, and make the GC have more work to do.

I plan to write an optimization guide on Crystal's docs soon.

I ran `wrk` and got better results, but I'm not sure I did it well. Could you try to run the benchmarks again with the changes in this PR?

### CODE REVIEW

**Comment by costajob** [comment]
@asterite Hi to you!

Indeed i was wondering how you in the Crystal community are so fast and kindly to help out developers approaching the language!
Considering i've posted just some minutes ago this is awesome! 
I'm now re-testing this with your optimisations and update my posts.

Many thanks

**Comment by asterite** [comment]
I just force-pushed some changes, I forgot to use the `to_json(io)` method in app.cr

**Comment by asterite** [comment]
I search `crystal-lang` or sometimes see some tweets about Crystal. If they say Crystal is slow, or at least  not as fast as one would expect, I take some time to see if things can be improved. This helps me see if the code can be made faster with some simple changes, or if there's a fundamental problem in the language's design or a performance bug in the standard library. So it's an easy way to improve the language performance :-)

Could you share with me the link to your tweet? I saw it some minutes ago but now I can't find it anywhere...

**Comment by costajob** [comment]
Thanks, sure here it is: https://twitter.com/agilestyle/status/745252724669878272

**Comment by costajob** [comment]
Hi,
 i just finished the benchmarks, now it's 10x faster than Ruby!
I am going to update my posts and README.
Thanks again for writing such a great language i will continue to support your work as i can!

**Comment by asterite** [comment]
Awesome!! 10x looks good :-)

**Pull request closed without merging**
